# config.toml

# The years are counted from zero, so, if we are 2025:
# 0 2025
# 1 2026
# 2 2027
# 3 2028
# 4 2029
# 5 2030
# 6                               
#
# --- A. Deterministic Inputs (Your Personal Financial Plan) ---

[deterministic_inputs]
I0 = 323700 # Initial Investment Value (e.g., EUR)
b0 = 24000  # Initial Bank Account Balance (e.g., EUR)

# Bank account lower and upper bound in real monaey 
# if it goes below it will be topped, if it goes above it will be invested
# from the investment
REAL_BANK_LOWER_BOUND_EUROS = 10_000
REAL_BANK_UPPER_BOUND_EUROS = 20_000

# Number of years the simulation will run
T_ret_years = 38

# In flows

# To the bank:
S_real_monthly = 0                               # Initial real monthly salary (e.g., 2500 EUR in today's money)   
SALARY_INFLATION_ADJUSTMENT_FACTOR = 1.0         # Factor by which salary adjusts to inflation (1.0 = same as inflation, 1.01 = 1% above inflation)
Y_S_start_idx = 0                                # Year index when salary starts (e.g., 0 for immediate start)
Y_S_end_idx = 0                                  # Year index when salary ends (e.g., 5 for 5 years of salary, exclusive of Year 5 itself)

# To the investment:
# Fixed monthly contribution to the invested assets, like a pak in today money
C_real_monthly_initial = 0 # Example: 500€ per month in today's money

# Planned Contributions, real amount. [[contrib, year], ...]
C_planned = [
    # Equivalent to 60,000€ nominal in Year 2 (assuming 2% inflation)
    # 60000 / (1.02)^2 = 60000 / 1.0404 = 57669.93 plus 16088 naspi already 
    # deflated
    [73_758, 2],
    # Equivalent to 60,000€ nominal in Year 3 (assuming 2% inflation)
    # 60000 / (1.02)^3 = 60000 / 1.061208 = 56538.96 plus 11382 naspi already 
    # deflated
    [67_920, 3],
    # Equivalent to 60,000€ nominal in Year 4 (assuming 2% inflation)
    # 60000 / (1.02)^4 = 60000 / 1.08243216 = 55430.35
    [55_430, 4],
]

# Out flows

# Fixed monthly exepense for the life level you want to keep
X_real_monthly_initial = 3300

# Planned Extra Expenses real_amount. [[X, year], ...]
# 0	1,00	100.000,00
# 1	1,02	98.039,22
# 2	1,04	96.116,88
# 3	1,06	94.232,23
# 4	1,08	92.384,54
# 5	1,10	90.573,08

X_planned_extra = [
    [100_000, 1],
]

H0_real_cost = 150_000 # Initial real cost of the house to be purchased at REBALANCING_YEAR_IDX

# The pension
P_real_monthly = 3900
PENSION_INFLATION_ADJUSTMENT_FACTOR = 0.6
Y_P_start_idx = 5

# --- B. Economic Assumptions (Averages and Volatilities) ---
# Nominal values
[economic_assumptions]
STOCK_MU = 0.095
STOCK_SIGMA = 0.14
BOND_MU = 0.05
BOND_SIGMA = 0.03
STR_MU = 0.008
STR_SIGMA = 0.012
FUN_MU = 0.253
FUN_SIGMA = 0.328
REAL_ESTATE_MU = -0.01
REAL_ESTATE_SIGMA = 0.08
mu_pi = 0.02
sigma_pi = 0.015

# --- C. Portfolio Allocations (Weights) ---
[portfolio_allocations]
REBALANCING_YEAR_IDX = 5
W_P1_STOCKS = 0.18
W_P1_BONDS = 0.28
W_P1_STR = 0.49
W_P1_FUN = 0.05
W_P1_REAL_ESTATE = 0.00

W_P2_STOCKS = 0.80
W_P2_BONDS = 0.20
W_P2_STR = 0.0
W_P2_FUN = 0.0
W_P2_REAL_ESTATE = 0.00

# W_P2_STOCKS = 0.60
# W_P2_BONDS = 0.40
# W_P2_STR = 0.00
# W_P2_FUN = 0.00
# W_P2_REAL_ESTATE = 0.0

# W_P2_STOCKS = 0.03
# W_P2_BONDS = 0.30
# W_P2_STR = 0.00 
# W_P2_FUN = 0.00
# W_P2_REAL_ESTATE = 0.67

# W_P2_STOCKS = 0.80
# W_P2_BONDS = 0.10
# W_P2_STR = 0.00
# W_P2_FUN = 0.10
# W_P2_REAL_ESTATE = 0.00

# --- D. Simulation Parameters ---
[simulation_parameters]
num_simulations = 10000

