[tool.black]
line-length = 100

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "firestarter"
version = "0.1.0b1"
description = "Monte Carlo simulation tool for FIRE (Financial Independence / Early Retirement) planning."
authors = [{ name = "aimer63", email = "imeriod@gmail.com" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy", "pandas", "matplotlib", "pydantic", "jinja2", "tomli"]

[project.scripts]
fire = "firestarter.main:main"
