from ignite.version import __version__
from datetime import datetime
from pathlib import Path

import jinja2


def generate_markdown_report(
    config_path: str,
    fire_stats: dict,
    output_dir: str,
    plots: dict[str, str] = None,
) -> str:
    if plots is None:
        plots = {}

    template_str = """
# FIRE Simulation Report

**Config:** `{{ config_path }}`
**Run date:** {{ run_date }}

## FIRE Plan Simulation Summary

- **Success Rate:** {{ fire_stats.success_rate | round(2) }}%
- **Number of failed simulations:** {{ fire_stats.failed_simulations_count }}
- **Average months lasted in failed simulations:** {{ fire_stats.avg_months_failed | round(1) }}

{% if fire_stats.worst_successful %}
### Worst Successful Case
- Final Wealth (Nominal): {{ "{:,.2f} EUR".format(fire_stats.worst_successful.final_wealth_nominal) }}
- Final Wealth (Real): {{ "{:,.2f} EUR".format(fire_stats.worst_successful.final_wealth_real) }}
- Your life CAGR: {{ (fire_stats.worst_successful.cagr * 100) | round(2) }}%
- Final Allocations: {{ fire_stats.worst_successful.allocations }}
{% endif %}

{% if fire_stats.average_successful %}
### Average Successful Case
- Final Wealth (Nominal): {{ "{:,.2f} EUR".format(fire_stats.average_successful.final_wealth_nominal) }}
- Final Wealth (Real): {{ "{:,.2f} EUR".format(fire_stats.average_successful.final_wealth_real) }}
- Your life CAGR: {{ (fire_stats.average_successful.cagr * 100) | round(2) }}%
- Final Allocations: {{ fire_stats.average_successful.allocations }}
{% endif %}

{% if fire_stats.best_successful %}
### Best Successful Case
- Final Wealth (Nominal): {{ "{:,.2f} EUR".format(fire_stats.best_successful.final_wealth_nominal) }}
- Final Wealth (Real): {{ "{:,.2f} EUR".format(fire_stats.best_successful.final_wealth_real) }}
- Your life CAGR: {{ (fire_stats.best_successful.cagr * 100) | round(2) }}%
- Final Allocations: {{ fire_stats.best_successful.allocations }}
{% endif %}

## Plots

{% for plot_name, plot_path in plots.items() %}
- [{{ plot_name }}]({{ plot_path }})
{% endfor %}

---

*Generated by FIRE Simulator v{{ version }} on {{ run_date }}*
"""

    context = {
        "config_path": config_path,
        "run_date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "fire_stats": fire_stats,
        "plots": plots,
        "version": __version__,
    }

    template = jinja2.Template(template_str)
    report_md = template.render(**context)

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    report_path = Path(output_dir) / f"summary_{datetime.now().strftime('%Y%m%d_%H%M')}.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_md)

    return str(report_path)
